apiVersion: kaptain.org/1.15
kind: layer-and-layerset-build
metadata:
  description: "Layerset composing quality and docker settings for image-environment-deploy images"

spec:
  layers:
    - layerset-and-layer-build:[1.4,2.0)
