apiVersion: kaptain.org/1.11
kind: docker-build-dockerfile
metadata:
  description: "Image environment deploy layerset - composes quality and docker build settings"

spec:
  layers:
    - layer-github-flow-strict:[1.3,2.0)
    - layer-image-environment-deploy:[1.3,2.0)
